spring:
  datasource:
  url: jdbc:h2:mem:products;DB_CLOSE_ON_EXIT=FALSE
  username: sa
  password:
  driver-class-name: org.h2.Driver
#  zipkin:
#    base-url: http://zipkin.default.svc:9411/
#    sender:
#      type: web
  sleuth:
    sampler:
      percentage: 1.0

server:
  port: 8101
opentracing:
  jaeger:
    http-sender:
      url: ${JAEGER_URL}

