spring:
#  zipkin:
#    base-url: http://zipkin.default.svc:9411/
#    sender:
#      type: web
  sleuth:
    sampler:
      percentage: 1.0

server:
  port: 8103

opentracing:
  jaeger:
    http-sender:
      url: ${JAEGER_URL}
