apiVersion: v1
kind: Endpoints
metadata:
  name: samples-clickhouse
  labels:
    app: clickhouse
    service: clickhouse
subsets:
  - addresses:
    - ip: 47.103.37.3
    ports:
    - name: chdb
      port: 8123
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: samples-clickhouse
  labels:
    app: clickhouse
    service: clickhouse
spec:
  ports:
  - port: 8123
    name: chdb
    targetPort: 8123
#  clusterIP: None
---

