eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${K8S_SAMPLES_DISCOVERY_SERVER_HOSTNAME:localhost}:8761/eureka/