# Copyright 2017 Istio Authors
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.

##################################################################################################
# This file defines the services, service accounts, and deployments for the Bookinfo sample.
#
# To apply all 4 Bookinfo services, their corresponding service accounts, and deployments:
#
#   kubectl apply -f samples/bookinfo/platform/kube/bookinfo.yaml
#
# Alternatively, you can deploy any resource separately:
#
#   kubectl apply -f samples/bookinfo/platform/kube/bookinfo.yaml -l service=reviews # reviews Service
#   kubectl apply -f samples/bookinfo/platform/kube/bookinfo.yaml -l account=reviews # reviews ServiceAccount
#   kubectl apply -f samples/bookinfo/platform/kube/bookinfo.yaml -l app=reviews,version=v3 # reviews-v3 Deployment
##################################################################################################
##################################################################################################
# API Gateway
##################################################################################################
apiVersion: v1
kind: Service
metadata:
  name: samples-api-gateway
  labels:
    app: gateway
    service: samples-api-gateway
spec:
  ports:
    - port: 10000
      name: http
      targetPort: 10000
    - port: 10010
      name: sidecar
      targetPort: 10010
  selector:
    app: gateway
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: samples-api-gateway-v1
  labels:
    app: gateway
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
      version: v1
  template:
    metadata:
      labels:
        app: gateway
        version: v1
        service: samples-api-gateway
      annotations:
        "flomesh.io/inject": "true"
        "flomesh.io/inject-cfg-type": "log-to-clickhouse"
    spec:
      containers:
        - name: gateway
          image: docker.io/flomesh/samples-api-gateway:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 10000
          env:
            - name: K8S_SAMPLES_DISCOVERY_SERVER_HOSTNAME
              value: samples-discovery-server
            - name: K8S_SAMPLES_DISCOVERY_SERVER_PORT
              value: "8771"
            - name: K8S_SERVICE_NAME
              value: samples-api-gateway
---

##################################################################################################
# Details service
##################################################################################################
apiVersion: v1
kind: Service
metadata:
  name: samples-bookinfo-details
  labels:
    app: details
    service: samples-bookinfo-details
spec:
  ports:
  - port: 8103
    name: http
    targetPort: 8103
  - port: 8113
    name: sidecar
    targetPort: 8113
  selector:
    app: details
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: samples-bookinfo-details-v1
  labels:
    app: details
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: details
      version: v1
  template:
    metadata:
      labels:
        app: details
        version: v1
        service: samples-bookinfo-details
      annotations:
        "flomesh.io/inject": "true"
        "flomesh.io/inject-cfg-type": "log-to-clickhouse"
    spec:
      containers:
      - name: details
        image: docker.io/flomesh/samples-bookinfo-details:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8103
        env:
          - name: K8S_SAMPLES_DISCOVERY_SERVER_HOSTNAME
            value: samples-discovery-server
          - name: K8S_SAMPLES_DISCOVERY_SERVER_PORT
            value: "8771"
          - name: K8S_SERVICE_NAME
            value: samples-bookinfo-details
---
##################################################################################################
# Ratings service
##################################################################################################
apiVersion: v1
kind: Service
metadata:
  name: samples-bookinfo-ratings
  labels:
    app: ratings
    service: samples-bookinfo-ratings
spec:
  ports:
  - port: 8101
    name: http
    targetPort: 8101
  - port: 8111
    name: sidecar
    targetPort: 8111
  selector:
    app: ratings
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: samples-bookinfo-ratings-v1
  labels:
    app: ratings
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ratings
      version: v1
  template:
    metadata:
      labels:
        app: ratings
        version: v1
        service: samples-bookinfo-ratings
      annotations:
        "flomesh.io/inject": "true"
        "flomesh.io/inject-cfg-type": "log-to-clickhouse"
    spec:
      containers:
      - name: ratings
        image: docker.io/flomesh/samples-bookinfo-ratings:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8101
        env:
          - name: K8S_SAMPLES_DISCOVERY_SERVER_HOSTNAME
            value: samples-discovery-server
          - name: K8S_SAMPLES_DISCOVERY_SERVER_PORT
            value: "8771"
          - name: K8S_SERVICE_NAME
            value: samples-bookinfo-ratings
---
##################################################################################################
# Reviews service
##################################################################################################
apiVersion: v1
kind: Service
metadata:
  name: samples-bookinfo-reviews
  labels:
    app: reviews
    service: samples-bookinfo-reviews
spec:
  ports:
  - port: 8102
    name: http
    targetPort: 8102
  - port: 8112
    name: sidecar
    targetPort: 8112
  selector:
    app: reviews
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: samples-bookinfo-reviews-v1
  labels:
    app: reviews
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reviews
      version: v1
  template:
    metadata:
      labels:
        app: reviews
        version: v1
        service: samples-bookinfo-reviews
      annotations:
        "flomesh.io/inject": "true"
        "flomesh.io/inject-cfg-type": "log-to-clickhouse"
    spec:
      containers:
      - name: reviews
        image: docker.io/flomesh/samples-bookinfo-reviews:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8102
        env:
          - name: K8S_SAMPLES_DISCOVERY_SERVER_HOSTNAME
            value: samples-discovery-server
          - name: K8S_SAMPLES_DISCOVERY_SERVER_PORT
            value: "8771"
          - name: K8S_SAMPLES_BOOKINFO_RATINGS_HOSTNAME
            value: samples-bookinfo-ratings
          - name: K8S_SAMPLES_BOOKINFO_RATINGS_PORT
            value: "8111"
          - name: K8S_SERVICE_NAME
            value: samples-bookinfo-reviews
---
##################################################################################################
# Productpage services
##################################################################################################
apiVersion: v1
kind: Service
metadata:
  name: samples-bookinfo-productpage
  labels:
    app: productpage
    service: samples-bookinfo-productpage
spec:
  ports:
  - port: 9080
    name: http
    targetPort: 9080
  - port: 9090
    name: sidecar
    targetPort: 9090
  selector:
    app: productpage
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: samples-bookinfo-productpage-v1
  labels:
    app: productpage
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: productpage
      version: v1
  template:
    metadata:
      labels:
        app: productpage
        version: v1
        service: samples-bookinfo-productpage
      annotations:
        "flomesh.io/inject": "true"
        "flomesh.io/inject-cfg-type": "log-to-clickhouse"
    spec:
      containers:
      - name: productpage
        env:
        - name: SERVICES_DOMAIN
          value: default.svc
        - name: DETAILS_HOSTNAME
          value: samples-bookinfo-details
        - name: RATINGS_HOSTNAME
          value: samples-bookinfo-ratings
        - name: REVIEWS_HOSTNAME
          value: samples-bookinfo-reviews
        - name: K8S_SERVICE_NAME
          value: samples-bookinfo-productpage
        image: docker.io/flomesh/samples-bookinfo-productpage:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 9080
---
