##################################################################################################
# Config service
##################################################################################################
apiVersion: v1
kind: Service
metadata:
  name: samples-config-service
  labels:
    app: config
    service: config
spec:
  ports:
    - port: 8888
      name: http
      targetPort: 8888
  selector:
    app: config
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: samples-config-service-v1
  labels:
    app: config
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: config
      version: v1
  template:
    metadata:
      labels:
        app: config
        version: v1
    spec:
      containers:
        - name: config
          image: docker.io/flomesh/samples-config-service:dev
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8888
          env:
            - name: K8S_SAMPLES_DISCOVERY_SERVER_HOSTNAME
              value: samples-discovery-server
            - name: K8S_SAMPLES_DISCOVERY_SERVER_PORT
              value: "8771"
            - name: K8S_SAMPLES_BOOKINFO_RATINGS_HOSTNAME
              value: samples-bookinfo-ratings
