##################################################################################################
# Discovery service
##################################################################################################
apiVersion: v1
kind: Service
metadata:
  name: samples-discovery-server
  labels:
    app: discovery
    service: discovery
spec:
  ports:
    - port: 8761
      name: http
      targetPort: 8761
  selector:
    app: discovery
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: samples-discovery-server-v1
  labels:
    app: discovery
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: discovery
      version: v1
  template:
    metadata:
      labels:
        app: discovery
        version: v1
    spec:
      containers:
        - name: discovery
          image: docker.io/flomesh/samples-discovery-server:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8761
          env:
            - name: K8S_SAMPLES_DISCOVERY_SERVER_HOSTNAME
              value: samples-discovery-server
