apiVersion: flomesh.io/v1alpha1
kind: ProxyProfile
metadata:
  name: proxy-profile-002-bookinfo
spec:
  selector:
    matchLabels:
      sys: bookinfo-samples
  namespace: flomesh-spring
  serviceEnv:
    - name: eureka.instance.metadataMap.mesh
      value: 'true'
    - name: eureka.instance.metadataMap.version
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.labels['version']
    - name: K8S_SAMPLES_DISCOVERY_SERVER_HOSTNAME
      value: '127.0.0.1'
    - name: K8S_SAMPLES_DISCOVERY_SERVER_PORT
      value: "8771"
  configUrl: http://10.0.0.60:6060/repo/spring
  sidecars:
#    - name: logger
#      imagePullPolicy: IfNotPresent
#      env:
#      - name: PIPY_SERVICE_NAME
#        valueFrom:
#          fieldRef:
#            fieldPath: metadata.annotations['service.flomesh.io/name']
#      - name: PIPY_LOG_SINK
#        value: "http://samples-clickhouse.flomesh-spring.svc:8123/?query=insert%20into%20log(message)%20format%20JSONAsString"
#      - name: PIPY_METRICS_SINK
#        value: "http://samples-metrics.flomesh-spring.svc:9001/metrics"
#      - name: PIPY_LOGGER_LISTEN
#        value: "9090"
    - name: proxy
      image: flomesh/pipy-pjs:0.4.0-184
      imagePullPolicy: IfNotPresent
      env:
      - name: PIPY_TARGET_HTTP_INBOUND_PORT
        valueFrom:
          fieldRef:
            apiVersion: v1
            fieldPath: metadata.annotations['service.flomesh.io/port']
      - name: SERVICE_VERSION
        valueFrom:
          fieldRef:
            apiVersion: v1
            fieldPath: metadata.labels['version']
      - name: PIPY_TARGET_EUREKA
        value: samples-discovery-server.flomesh-spring:8761
      - name: PIPY_CONFIG
        value: "http://samples-config.flomesh-spring.svc:9000/config"