spring:
  datasource:
  url: jdbc:h2:mem:products;DB_CLOSE_ON_EXIT=FALSE
  username: sa
  password:
  driver-class-name: org.h2.Driver
server:
  port: 8101
opentracing:
  jaeger:
    http-sender:
      url: http://localhost:14268/api/traces
