spring:
  datasource:
  url: jdbc:h2:mem:products;DB_CLOSE_ON_EXIT=FALSE
  username: sa
  password:
  driver-class-name: org.h2.Driver
  application:
    name: bookinfo-ratings
server:
  port: 8101
opentracing:
  jaeger:
    http-sender:
      url: ${JAEGER_URL}
