spring:
  application:
    name: config-service
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/samples-config

eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    gZipContent: false
    serviceUrl:
      defaultZone: http://${K8S_SAMPLES_DISCOVERY_SERVER_HOSTNAME:localhost}:${K8S_SAMPLES_DISCOVERY_SERVER_PORT:8761}/eureka/

server:
  port: 8888
